### ISSUE TITLE
Hi ,那个养眼项目已经停止维护了,新版本请到https://github.com/miaoMiaoDaShi/YangYanNew参看

### ISSUE THREAD

**Issue by miaoMiaoDaShi** [live17909/MyMvArms#1]

**Comment by miaoMiaoDaShi** [comment]
thinks,star

**Comment by a1105440231** [comment]
Dagger does not support injection into private fields
    private com.jess.arms.integration.AppManager mAppManager;

大神有遇到这样的情况吗

**Comment by miaoMiaoDaShi** [comment]
很明显了,你申明了 private,注解处理这种,都不支持 private 属性的  比如 Butterknife
